### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by felipesabino** [jxcore/wifi-shoplist-app#1]
This repo is being linked from both [iOs](https://itunes.apple.com/us/app/wifi-shoplist/id1022813783) and [Android](https://play.google.com/store/apps/details?id=com.nubisa.WiFiShoplist) apps both the repo is just empty.

Are there any concrete plans on adding the source here?

**Comment by pkoretic** [comment]
+1

**Comment by obastemur** [comment]
Pushed the source codes. Thanks for the reminder.
